// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi 3 Simple Job
A simple Rest-Api to submit Fibonacci Job through Stack.


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.1.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
