// Code generated by go-swagger; DO NOT EDIT.

package lists

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"3_simple/models"
)

// FindListOKCode is the HTTP code returned for type FindListOK
const FindListOKCode int = 200

/*FindListOK list all jobs

swagger:response findListOK
*/
type FindListOK struct {

	/*
	  In: Body
	*/
	Payload models.FindListOKBody `json:"body,omitempty"`
}

// NewFindListOK creates FindListOK with default headers values
func NewFindListOK() *FindListOK {
	return &FindListOK{}
}

// WithPayload adds the payload to the find list o k response
func (o *FindListOK) WithPayload(payload models.FindListOKBody) *FindListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find list o k response
func (o *FindListOK) SetPayload(payload models.FindListOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.FindListOKBody, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*FindListDefault generic error response

swagger:response findListDefault
*/
type FindListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewFindListDefault creates FindListDefault with default headers values
func NewFindListDefault(code int) *FindListDefault {
	if code <= 0 {
		code = 500
	}

	return &FindListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the find list default response
func (o *FindListDefault) WithStatusCode(code int) *FindListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the find list default response
func (o *FindListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the find list default response
func (o *FindListDefault) WithPayload(payload *models.Error) *FindListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the find list default response
func (o *FindListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *FindListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
