// Code generated by go-swagger; DO NOT EDIT.

package lists

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// FindListHandlerFunc turns a function with the right signature into a find list handler
type FindListHandlerFunc func(FindListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindListHandlerFunc) Handle(params FindListParams) middleware.Responder {
	return fn(params)
}

// FindListHandler interface for that can handle valid find list params
type FindListHandler interface {
	Handle(FindListParams) middleware.Responder
}

// NewFindList creates a new http.Handler for the find list operation
func NewFindList(ctx *middleware.Context, handler FindListHandler) *FindList {
	return &FindList{Context: ctx, Handler: handler}
}

/*FindList swagger:route GET / lists findList

FindList find list API

*/
type FindList struct {
	Context *middleware.Context
	Handler FindListHandler
}

func (o *FindList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFindListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
