// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi High Performance Computing - Rest Api - CPU247
A Rest-Api to submit HPC-Jobs.


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.0.1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
