// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A Rest-Api to submit HPC-Jobs.",
    "title": "High Performance Computing - Rest Api - CPU247",
    "version": "0.0.1"
  },
  "paths": {
    "/": {
      "get": {
        "tags": [
          "jobs"
        ],
        "operationId": "findJobs",
        "parameters": [
          {
            "type": "string",
            "name": "search",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "name": "page",
            "in": "query"
          },
          {
            "type": "integer",
            "format": "int64",
            "default": 20,
            "name": "page_size",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "list the job operations",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/job"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "post": {
        "tags": [
          "jobs"
        ],
        "operationId": "addOne",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/job"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/job"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/{id}": {
      "put": {
        "tags": [
          "jobs"
        ],
        "operationId": "updateOne",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/job"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/job"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "delete": {
        "tags": [
          "jobs"
        ],
        "operationId": "destroyOne",
        "responses": {
          "204": {
            "description": "Deleted"
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      },
      "parameters": [
        {
          "type": "integer",
          "format": "int64",
          "name": "id",
          "in": "path",
          "required": true
        }
      ]
    }
  },
  "definitions": {
    "archiveFilters": {
      "type": "string"
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "job": {
      "type": "object",
      "required": [
        "id",
        "name"
      ],
      "properties": {
        "archiveFilters": {
          "description": "Filters on job visibility related to whether it is archived",
          "type": "array",
          "items": {
            "$ref": "#/definitions/archiveFilters"
          }
        },
        "caseFile": {
          "description": "File with case variables for DOE job",
          "type": "object"
        },
        "expectedRuns": {
          "description": "Number of runs for a DOE, will be 1 for basic jobs",
          "type": "integer"
        },
        "id": {
          "description": "Job identifier",
          "type": "string",
          "readOnly": true
        },
        "includeNominalRun": {
          "description": "Whether to include a nominal baseline run for a DOE job",
          "type": "boolean"
        },
        "isLowPriority": {
          "description": "Is this a low priority job?",
          "type": "boolean"
        },
        "isTemplateDryRun": {
          "description": "Run this job in “dry run” mode to check DOE templates",
          "type": "boolean"
        },
        "jobanalyses": {
          "description": "List of analyses for the job. Details below",
          "type": "array",
          "items": {
            "$ref": "#/definitions/jobanalyses"
          }
        },
        "jobvariables": {
          "description": "List of job variables for DOE job. Details below",
          "type": "array",
          "items": {
            "$ref": "#/definitions/jobvariables"
          }
        },
        "monteCarloIterations": {
          "description": "Number of iterations for Monte Carlo optimization job",
          "type": "integer"
        },
        "name": {
          "description": "Name of job",
          "type": "string"
        },
        "optimizer": {
          "description": "Job analysis representing optimizer used for optimization jobs",
          "type": "object"
        },
        "owner": {
          "description": "Email address of job owner",
          "type": "string"
        },
        "paramFile": {
          "description": "CSV file with DOE parameters (DOE job only)",
          "type": "object"
        },
        "remoteVizConfig": {
          "description": "(deprecated) Configuration for companion remote visualization node",
          "type": "object"
        },
        "resourceFilters": {
          "description": "Filters on file resources",
          "type": "array",
          "items": {
            "$ref": "#/definitions/resourceFilters"
          }
        }
      }
    },
    "jobanalyses": {
      "type": "object"
    },
    "jobvariables": {
      "type": "object"
    },
    "resourceFilters": {
      "type": "object"
    }
  }
}`))
}
