swagger: "2.0"
info:
  description: A Rest-Api to submit HPC-Jobs.
  title: High Performance Computing - Rest Api - CPU247
  version: 0.0.1
consumes:
- application/json
produces:
- application/json
schemes:
- http
paths:
  /:
    get:
      tags:
        - jobs
      operationId: findJobs
      parameters:
        - name: search
          in: query
          type: string
        - name: page
          in: query
          type: integer
          format: int64
        - name: page_size
          in: query
          type: integer
          format: int64
          default: 20
      responses:
        200:
          description: list the job operations
          schema:
            type: array
            items:
              $ref: "#/definitions/job"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - jobs
      operationId: addOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/job"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/job"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /{id}:
    parameters:
      - type: integer
        format: int64
        name: id
        in: path
        required: true
    put:
      tags:
        - jobs
      operationId: updateOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/job"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/job"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
    delete:
      tags:
        - jobs
      operationId: destroyOne
      responses:
        204:
          description: Deleted
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
definitions:
  archiveFilters:
    type: string
  jobanalyses:
    type: object
    # TODO
  jobvariables:
    type: object
    # TODO
  resourceFilters:
    type: object
    # TODO
  job:
    type: object
    required:
      - name
    properties:
      archiveFilters:
        type: array
        items:
          $ref: "#/definitions/archiveFilters"
        description: Filters on job visibility related to whether it is archived
      caseFile:
        type: object
        description: File with case variables for DOE job
      expectedRuns:
        type: integer
        description: Number of runs for a DOE, will be 1 for basic jobs
      id:
        type: integer
        description: Job identifier
        readOnly: true
      includeNominalRun:
        type: boolean
        description: Whether to include a nominal baseline run for a DOE job
      isLowPriority:
        type: boolean
        description: Is this a low priority job?
      isTemplateDryRun:
        type: boolean
        description: Run this job in “dry run” mode to check DOE templates
      jobanalyses:
        type: array
        items:
          $ref: "#/definitions/jobanalyses"
        description: List of analyses for the job. Details below
      jobvariables:
        type: array
        items:
          $ref: "#/definitions/jobvariables"
        description: List of job variables for DOE job. Details below
      monteCarloIterations:
        type: integer
        description: Number of iterations for Monte Carlo optimization job
      name:
        type: string
        description: Name of job
      optimizer:
        type: object
        description: Job analysis representing optimizer used for optimization jobs
      owner:
        type: string
        description: Email address of job owner
      paramFile:
        type: object
        description: CSV file with DOE parameters (DOE job only)
      remoteVizConfig:
        type: object
        description: (deprecated) Configuration for companion remote visualization node
      resourceFilters:
        type: array
        items:
          $ref: "#/definitions/resourceFilters"
        description: Filters on file resources
      # jobvariables:
      #   type: None
      #   description: No
      # jobanalyses:
      #   type: None
      #   description: Yes
      # resourceFilters:
      #   type: Default filters
      #   description: No
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
