// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Jobvariables jobvariables
// swagger:model jobvariables
type Jobvariables interface{}
