// Code generated by go-swagger; DO NOT EDIT.

package jobs

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// FindJobsHandlerFunc turns a function with the right signature into a find jobs handler
type FindJobsHandlerFunc func(FindJobsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn FindJobsHandlerFunc) Handle(params FindJobsParams) middleware.Responder {
	return fn(params)
}

// FindJobsHandler interface for that can handle valid find jobs params
type FindJobsHandler interface {
	Handle(FindJobsParams) middleware.Responder
}

// NewFindJobs creates a new http.Handler for the find jobs operation
func NewFindJobs(ctx *middleware.Context, handler FindJobsHandler) *FindJobs {
	return &FindJobs{Context: ctx, Handler: handler}
}

/*FindJobs swagger:route GET / jobs findJobs

FindJobs find jobs API

*/
type FindJobs struct {
	Context *middleware.Context
	Handler FindJobsHandler
}

func (o *FindJobs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewFindJobsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
